### ISSUE TITLE
Root swagger file in subdir

### ISSUE THREAD

**Issue by wingedfox** [apigee-127/sway#110]
Hi,

I'm not sure whether this should be fixed in `swagger-node-runner` or in `sway`, but I could not serve swagger docs with $ref's from a subdirectory.

**Config**

``` js
var seConfig = {
  appRoot: __dirname, // required config
  swagger: 'api-docs/api-doc.yml'
};
```

**1st case**

_Root doc_

``` yaml
paths:
  /: 
    $ref: ./api-docs/paths/discovery.yml
```

_Error_

```
Error in callback! Tossing to global error handler. TypeError: Cannot read property 'consumes' of undefined
    at new Operation (/home/ilya/Workspace/storage/node_modules/sway/lib/types/operation.js:65:29)
```

_`api.definitionRemoteResolves`_

```
  paths:
   { '/': { '$ref': './api-docs/paths/discovery.yml' }
```

**2nd case**

_Root doc_

``` yaml
paths:
  /: 
    $ref: ./paths/discovery.yml
```

_Error_

```
Error in callback! Tossing to global error handler. Error: Swagger validation errors:
    at /home/ilya/Workspace/storage/node_modules/swagger-node-runner/index.js:210:23
Details:
        #0.: Reference could not be resolved: ./paths/discovery.yml in swagger config at: >paths///$ref<
```

_`api.definitionRemoteResolves`_

```
paths: { '/': { get: [Object] }
```

**Comment by whitlockjc** [comment]
This is related to #101.
